[32m2025-05-19 16:06:19 +0900[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - a79ff986-d450-46b7-adc5-723a07a576e9 - 19651 - LOGS_CAPTURED - Started capturing logs in process (pid: 19651).
[32m2025-05-19 16:06:19 +0900[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - a79ff986-d450-46b7-adc5-723a07a576e9 - 19651 - get_dataframe_from_clickhouse - STEP_START - Started execution of step "get_dataframe_from_clickhouse".
[32m2025-05-19 16:06:19 +0900[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - a79ff986-d450-46b7-adc5-723a07a576e9 - get_dataframe_from_clickhouse - Loading file from: /home/wnsgu/slife-dag-engine/.tmp_dagster_home_kwn10y5y/storage/table_name using PickledObjectFilesystemIOManager...
[32m2025-05-19 16:06:19 +0900[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - a79ff986-d450-46b7-adc5-723a07a576e9 - 19651 - get_dataframe_from_clickhouse - LOADED_INPUT - Loaded input "table_name" using input manager "io_manager", from output "result" of step "table_name"
[32m2025-05-19 16:06:19 +0900[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - a79ff986-d450-46b7-adc5-723a07a576e9 - 19651 - get_dataframe_from_clickhouse - STEP_INPUT - Got input "table_name" of type "String". (Type check passed).
[32m2025-05-19 16:06:19 +0900[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - a79ff986-d450-46b7-adc5-723a07a576e9 - 19651 - get_dataframe_from_clickhouse - STEP_FAILURE - Execution of step "get_dataframe_from_clickhouse" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "get_dataframe_from_clickhouse"::

AttributeError: module 'datetime' has no attribute 'now'

Stack Trace:
  File "/home/wnsgu/.pyenv/versions/3.11.0/envs/clickhouse_env/lib/python3.11/site-packages/dagster/_core/execution/plan/utils.py", line 56, in op_execution_error_boundary
    yield
  File "/home/wnsgu/.pyenv/versions/3.11.0/envs/clickhouse_env/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 392, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/home/wnsgu/.pyenv/versions/3.11.0/envs/clickhouse_env/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 129, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/home/wnsgu/.pyenv/versions/3.11.0/envs/clickhouse_env/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 117, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wnsgu/slife-dag-engine/dags/load_ast.py", line 73, in get_dataframe_from_clickhouse
    df_log = process_load(df, table_name, case_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wnsgu/slife-dag-engine/dags/load_ast.py", line 24, in process_load
    start_load = datetime.now()
                 ^^^^^^^^^^^^
[0m
